version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/graph-data.rs"
    schedule:
      interval: "daily"
    reviewers:
      - "wking"
      - "vrutkovs"
      - "PratikMahajan"
      - "LalatenduMohanty"
