to: 4.11.6
from: 4[.]10[.].*
url:  https://issues.redhat.com/browse/MCO-457
name: MachineConfigRenderingChurn
message: |-
  Clusters with KubletConfigs that do not set 'CSIMigrationOpenStack: true' should remain on 4.10 until they can update to a 4.11 that contains a fix.  Clusters that do not contain any KubeletConfigs are unlikely to be exposed.
matchingRules:
- type: PromQL
  promql:
    promql:
      group(cluster:usage:resources:sum{resource="kubeletconfigs.machineconfiguration.openshift.io"} > 0)
      or
      0 * group(cluster:usage:resources:sum)
