to: 4.12.6
from: .*
url: https://issues.redhat.com/browse/OCPNODE-1502
name: LeakedMachineConfigBlocksMCO
message: |-
  Machine Config Operator stalls when encountering orphaned KubeletConfig or ContainerRuntimeConfig resources.
matchingRules:
- type: PromQL
  promql:
    promql:
      group(cluster:usage:resources:sum{resource=~"(containerruntimeconfigs|kubeletconfigs)[.]machineconfiguration[.]openshift[.]io"} > 0)
      or
      0 * group(cluster:usage:resources:sum)
