to: 4.16.7
from: ^4[.](15[.]([1]?[0-9]|2[0-4])|16[.][0-6])[+].*$
url: https://issues.redhat.com/browse/NHE-1171
name: SRIOVFailedToConfigureVF
fixedIn: 4.16.8
message: |-
  OCP Versions 4.14.34, 4.15.25, 4.16.7 and ALL subsequent versions include kernel datastructure changes which are not compatible with older versions of the SR-IOV operator. Please update SR-IOV operator to versions dated 20240826 or newer before updating OCP.
matchingRules:
- type: PromQL
  promql:
    promql: |
      group(csv_succeeded{_id="", name=~"sriov-network-operator[.].*"})
      or
      0 * group(csv_count{_id=""})
