apiVersion: updateservice.operator.openshift.io/v1
kind: UpdateService
metadata:
  name: example
  namespace: openshift-update-service
spec:
  graphDataImage: >-
    image-registry.openshift-image-registry.svc:5000/openshift-update-service/graph-data:latest
  releases: quay.io/openshift-release-dev/ocp-release
  replicas: 1
