[package]
name = "cincinnati-graph-data"
version = "0.1.0"
authors = ["Vadim Rutkovsky <vrutkovs@redhat.com>"]
edition = "2018"

[dependencies]
cincinnati = { git = "https://github.com/openshift/cincinnati", rev = "dc2abd15d0336318829e6788000ac7418c29c2fc"}
actix-http = "^3.7.0"
actix-service = "=2.0.2"
tokio = { version = "^1.14", features = [ "fs", "rt-multi-thread" ] }
serde = "^1.0.203"
serde_yaml = "^0.9.34"
anyhow = "1.0"
regex = "^1.10.5"
semver = { version = "^0.11", features = [ "serde" ] }
toml = "^0.8.14"
lazy_static = "^1.4.0"
url = "^2.5.2"
reqwest = { version = "^0.11", features = ["gzip"] }
futures = "^0.3"
itertools = "^0.13"
zeroize = "=1.3.0"
test-case = "^3.3.1"
