[package]
name = "cincinnati-graph-data"
version = "0.1.0"
authors = ["Vadim Rutkovsky <vrutkovs@redhat.com>"]
edition = "2018"

[dependencies]
cincinnati = { git = "https://github.com/openshift/cincinnati", rev = "003953928adc5a2a5a244c4fd8c6bb8b038490e8"}
tokio = { version = "1.0", features = [ "fs" ] }
serde = "^1.0.125"
serde_yaml = "^0.8.17"
anyhow = "1.0"
regex = "^1.4.5"
semver = { version = "^0.11", features = [ "serde" ] }
toml = "^0.5.8"
lazy_static = "^1.2.0"
url = "^2.2.1"
reqwest = { version = "^0.11", features = ["gzip"] }
futures = "^0.3"
itertools = "^0.10"
